### ISSUE TITLE
X-Frame-Options

### ISSUE THREAD

**Issue by JosefJezek** [mainwp/mainwp-child#2]
Could you add option to child for disable X-Frame-Options ALLOWALL?
https://github.com/mainwp/mainwp-child/blob/master/mainwp-child.php#L10

I need set own X-Frame-Options on server.

In future add CSP1.1 frame-ancestors.

**Comment by steveni1963** [comment]
I have raised a query with support over the same issue.  All my child wordpress sites now are running with dual X-Frame-Options as was already set on the server.  Found because chrome wouldn't load popup in backend editor and debug showed the error due to ALLOWALL and SAMEORIGIN being set in the header.

**Comment by bogdan-mainwp** [comment]
This issue has been fixed in one of our previous versions.
