### ISSUE TITLE
Incorrect url on plugin installation page

### ISSUE THREAD

**Issue by sallec** [mainwp/mainwp-child#254]
This is minor, non critical bug, wrong url to Bulk Settings Extension page.

To reproduce, go to Install plugin page and install some plugins to some sites.
On that page titled "Plugin installation", you will see text in a blue box with content:
"Did you know with the Bulk Settings Extension you can control the settings of this plugin directly from your MainWP Dashboard?"
Url for "Bulk Settings Extension" is incorrect (or redirection is incorrect).
https://mainwp.com/extensions/bulk-settings-manager redirects to https://mainwp.com/bulk-settings-manager-2/#main which is non existent page, but it should probably redirect to a page https://mainwp.com/extension/bulk-settings-manager/

If you don't want me to report this minor bugs, let me know.
Thank you.

**Comment by sallec** [comment]
Or should I use tickets to report this kind of bugs?

**Comment by bogdan-mainwp** [comment]
Hi @sallec,

thanks for reporting this. 

I have placed the correct redirection now, but the URL will be fixed in code and the fix will be included in the next release.

You are very welcome to report any bug, we appreciate that. Also, if you want and have time, small problems that you find and know how to fix, you can create Pull Request. However, if you prefer just to report problems, it may be better to use our standard [Helpdesk ticket form](https://mainwp.com/my-account/get-support/). 

Thanks.

**Comment by bogdan-mainwp** [comment]
URL updated, [preview available here](https://github.com/mainwp/mainwp/commit/2a5f04dab19690748396d44e039e92173d5e9ff4).

**Comment by sallec** [comment]
Hi @bogdan-mainwp ,
I still didn't had time to check thru the code but i have some ideas about extending code functionality. I will remember your suggestion about creating Pull Requests.
Thanks.
